// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI2UPMpV0Zz44XVmoigfr7eRA56214_F4',
    appId: '1:797299572751:web:9085a533e75878c007237a',
    messagingSenderId: '797299572751',
    projectId: 'discussion-1ba60',
    authDomain: 'discussion-1ba60.firebaseapp.com',
    storageBucket: 'discussion-1ba60.firebasestorage.app',
    measurementId: 'G-1K3BSY2RPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuxNpzoBG08TsxYoBuirscH2NIU-2nbkA',
    appId: '1:797299572751:android:a0a769280953352107237a',
    messagingSenderId: '797299572751',
    projectId: 'discussion-1ba60',
    storageBucket: 'discussion-1ba60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bqd1c6gS7DkPHigUAsYXu5yFXxf-VtI',
    appId: '1:797299572751:ios:c2e9405b2f5a355907237a',
    messagingSenderId: '797299572751',
    projectId: 'discussion-1ba60',
    storageBucket: 'discussion-1ba60.firebasestorage.app',
    iosBundleId: 'com.example.discussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1bqd1c6gS7DkPHigUAsYXu5yFXxf-VtI',
    appId: '1:797299572751:ios:c2e9405b2f5a355907237a',
    messagingSenderId: '797299572751',
    projectId: 'discussion-1ba60',
    storageBucket: 'discussion-1ba60.firebasestorage.app',
    iosBundleId: 'com.example.discussion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI2UPMpV0Zz44XVmoigfr7eRA56214_F4',
    appId: '1:797299572751:web:b692bc47f84c80e707237a',
    messagingSenderId: '797299572751',
    projectId: 'discussion-1ba60',
    authDomain: 'discussion-1ba60.firebaseapp.com',
    storageBucket: 'discussion-1ba60.firebasestorage.app',
    measurementId: 'G-KTY76W3WD8',
  );
}
